### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by SOF3** [dihydrogen-monoxide/XialotEcon#1]
- [x] This repo has no code, so no servers can run it!
- [x] This repo has no license, so nobody can use it!
- [x] This repo has no outline, so no brains can imagine it!
- [ ] This repo has no printed copies, so no apocalypse survivors can know its existence!

**Comment by HittmanA** [comment]
Done :D

**Comment by SOF3** [comment]
> This repo has no printed copies, so no apocalypse survivors can know its existence!

This is done?

**Comment by HittmanA** [comment]
I assumed you didn't *actually* mean print out the readme. But I guess I can see about it.
